import{a as w,S as P,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const S="56868862-3dcc84f72f876530e5630b5a4",b="https://pixabay.com/api/";async function m(r,o=1){const a={key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await w.get(b,{params:a})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function p(r){const o=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:i,comments:y,downloads:L})=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${s}">
                        <img class="gallery-image" src="${a}" alt="${e}" />
                    </a>
                    <ul class="info-container">
                        <li class="info-item"><h3>Likes</h3> <p>${t}</p></li>
                        <li class="info-item"><h3>Views</h3> <p>${i}</p></li>
                        <li class="info-item"><h3>Comments</h3> <p>${y}</p></li>
                        <li class="info-item"><h3>Downloads</h3> <p>${L}</p></li>
                    </ul>
                </li>
                `).join(" ");u.insertAdjacentHTML("beforeend",o),q.refresh()}function v(){u.innerHTML=""}function g(){f.classList.remove("hidden")}function h(){f.classList.add("hidden")}let d=1,c="";const l=document.querySelector(".ja-load-more");l.addEventListener("click",O);h();const $=document.querySelector(".form");$.addEventListener("submit",E);async function E(r){r.preventDefault();const o=r.currentTarget;if(c=o.elements["search-text"].value.trim(),c===""){n.warning({title:"Caution",message:"Please enter a search term!",position:"topRight"});return}d=1,l.classList.replace("load-more","load-more-hidden"),v(),g();try{const a=await m(c,d);if(a.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(a.hits),a.hits.length===15&&l.classList.replace("load-more-hidden","load-more")}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{o.reset(),h()}}async function O(){d+=1,g(),l.classList.replace("load-more","load-more-hidden");try{const r=await m(c,d);if(p(r.hits),r.hits.length<15){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}l.classList.replace("load-more-hidden","load-more")}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}}
//# sourceMappingURL=index.js.map
