import{a as b,S as M,i}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const q="56868862-3dcc84f72f876530e5630b5a4",v="https://pixabay.com/api/";async function h(a,t=1){const o={key:q,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await b.get(v,{params:o})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".ja-load-more"),R=new M(".gallery a",{captionsData:"alt",captionDelay:250});function p(a){const t=a.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:l,comments:P,downloads:S})=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${s}">
                        <img class="gallery-image" src="${o}" alt="${e}" />
                    </a>
                    <ul class="info-container">
                        <li class="info-item"><h3>Likes</h3> <p>${r}</p></li>
                        <li class="info-item"><h3>Views</h3> <p>${l}</p></li>
                        <li class="info-item"><h3>Comments</h3> <p>${P}</p></li>
                        <li class="info-item"><h3>Downloads</h3> <p>${S}</p></li>
                    </ul>
                </li>
                `).join(" ");m.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){m.innerHTML=""}function y(){f.classList.remove("hidden")}function u(){f.classList.add("hidden")}function L(){g.classList.replace("load-more-hidden","load-more")}function c(){g.classList.replace("load-more","load-more-hidden")}let n=1,d="";const w=15,E=document.querySelector(".ja-load-more");E.addEventListener("click",T);u();c();const H=document.querySelector(".form");H.addEventListener("submit",O);async function O(a){a.preventDefault();const t=a.currentTarget;if(d=t.elements["search-text"].value.trim(),d===""){i.warning({title:"Caution",message:"Please enter a search term!",position:"topRight"});return}n=1,c(),$(),y();try{const o=await h(d,n);if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(o.hits);const s=Math.ceil(o.totalHits/w);n>=s?(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):L()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{t.reset(),u()}}async function T(){n+=1,y(),c();try{const a=await h(d,n);p(a.hits);const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}const o=Math.ceil(a.totalHits/w);if(n>=o){i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c();return}L()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
