import{a as b,S as v,i}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const M="56868862-3dcc84f72f876530e5630b5a4",q="https://pixabay.com/api/";async function h(s,t=1){const o={key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await b.get(q,{params:o})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".js-load-more"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(s){const t=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:r,views:c,comments:P,downloads:S})=>`
                <li class="gallery-item">
                    <a class="gallery-link" href="${a}">
                        <img class="gallery-image" src="${o}" alt="${e}" />
                    </a>
                    <ul class="info-container">
                        <li class="info-item"><h3>Likes</h3> <p>${r}</p></li>
                        <li class="info-item"><h3>Views</h3> <p>${c}</p></li>
                        <li class="info-item"><h3>Comments</h3> <p>${P}</p></li>
                        <li class="info-item"><h3>Downloads</h3> <p>${S}</p></li>
                    </ul>
                </li>
                `).join(" ");m.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){m.innerHTML=""}function y(){f.classList.remove("hidden")}function u(){f.classList.add("hidden")}function L(){g.classList.remove("load-more-hidden")}function l(){g.classList.add("load-more-hidden")}let n=1,d="";const w=15,E=document.querySelector(".js-load-more");E.addEventListener("click",T);u();l();const H=document.querySelector(".form");H.addEventListener("submit",O);async function O(s){s.preventDefault();const t=s.currentTarget;if(d=t.elements["search-text"].value.trim(),d===""){i.warning({title:"Caution",message:"Please enter a search term!",position:"topRight"});return}n=1,l(),$(),y();try{const o=await h(d,n);if(o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(o.hits);const a=Math.ceil(o.totalHits/w);n>=a?(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l()):L()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{t.reset(),u()}}async function T(){n+=1,y(),l();try{const s=await h(d,n);p(s.hits);const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}const o=Math.ceil(s.totalHits/w);if(n>=o){i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l();return}L()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
